default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 3306 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "mysql" } %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV.fetch("DB_DATABASENAME") %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("DB_DATABASENAME") %>_test

production:
  <<: *default
